<script>
  export let style = null;
</script>

<div class='lorem-block' {style}>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla at volutpat diam ut venenatis tellus in metus. Molestie nunc non blandit massa enim nec dui. Orci ac auctor augue mauris augue neque gravida in. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. A diam maecenas sed enim ut sem. Scelerisque in dictum non consectetur a erat nam. Cursus eget nunc scelerisque viverra mauris. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Mauris rhoncus aenean vel elit scelerisque mauris. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Tellus integer feugiat scelerisque varius morbi enim nunc.
  Consectetur adipiscing elit ut aliquam purus sit amet. Interdum velit euismod in pellentesque. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Tortor at auctor urna nunc id. Ullamcorper dignissim cras tincidunt lobortis feugiat. Integer enim neque volutpat ac tincidunt. In nibh mauris cursus mattis molestie a iaculis. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Consectetur purus ut faucibus pulvinar elementum. Ultricies tristique nulla aliquet enim.  
  Ultrices eros in cursus turpis. Sed cras ornare arcu dui. Neque convallis a cras semper. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Posuere morbi leo urna molestie at elementum eu facilisis. Tellus mauris a diam maecenas sed enim ut sem viverra. Ornare suspendisse sed nisi lacus sed viverra tellus in. Sit amet est placerat in egestas erat imperdiet sed. Nisi quis eleifend quam adipiscing. Diam maecenas sed enim ut sem viverra. Eu consequat ac felis donec et. Eget nullam non nisi est sit amet. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Phasellus egestas tellus rutrum tellus pellentesque. Quisque non tellus orci ac auctor. Nunc congue nisi vitae suscipit tellus mauris. Mauris commodo quis imperdiet massa tincidunt. Nunc sed velit dignissim sodales ut eu.  
  Proin fermentum leo vel orci porta non pulvinar. Nisl purus in mollis nunc sed id. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Et netus et malesuada fames ac turpis egestas. Pretium fusce id velit ut tortor pretium viverra suspendisse. Nec tincidunt praesent semper feugiat. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Risus quis varius quam quisque id diam vel quam elementum. Scelerisque in dictum non consectetur a erat. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Ac turpis egestas maecenas pharetra convallis. Volutpat lacus laoreet non curabitur gravida arcu ac. Sapien eget mi proin sed libero enim sed.  
  Morbi tempus iaculis urna id volutpat lacus laoreet. Varius quam quisque id diam vel quam elementum pulvinar. In arcu cursus euismod quis viverra nibh cras. Lobortis mattis aliquam faucibus purus in. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Amet aliquam id diam maecenas ultricies mi eget. Varius sit amet mattis vulputate. Odio morbi quis commodo odio aenean sed adipiscing. Tristique magna sit amet purus gravida quis blandit turpis. At urna condimentum mattis pellentesque.
</div>

<style lang='scss' scoped>
  .lorem-block{
    margin: 10px 0;
  }
</style>